replicaCount: 2

image:
  repository: AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/eks-platform-dev
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  APP_VERSION: "1.0.0"
